name: ${project.name}
main: com.github.igotyou.FactoryMod.FactoryMod
author: igotyou
version: ${project.version}
depend: [CivModCore]
softdepend: [CivMenu, NameLayer, Citadel]
commands:
    fm:
        permission: fm.public
    fmc:
        permission: fm.op
permissions:
    fm.public:
        default: true
    fm.op:
        default: op